=== billygoat891/billygoat891.github.io/activity_centers/Start/StartPage/start.dtd
<!ELEMENT SECTION       (HEAD, IMAGES?, ITEMS?, LOC*) >

<!-- SECTION[VISIBLE]: Controls visibility of this section -->
<!-- SECTION[SELECTIVE]: Controls whether users can control visibility
     of individual items (default SELECTIVE) -->
<!-- SECTION[STYLE]: Specifies which section this is (for picky stylesheets) -->
<!-- SECTION[PRIMARY]: Specifies thiat this is a primary section (more prominent) -->
<!-- SECTION[ADAPT]: Specifies whether the file should be adaptive or static -->
<!-- SECTION[MORETARGET]: The folder to open if there is more -->
<!ATTLIST SECTION
    VISIBLE (0|1)       "1"
    SELECTIVE (0|1)     "1"
    STYLE   (ispbanner|startpl|myprograms|companybanner) #REQUIRED
    PRIMARY  (0|1)      "0"
    ADAPT    (0|1)      #IMPLIED
    MORETARGET CDATA    #IMPLIED>

<!-- HEAD: Header info -->
<!ELEMENT HEAD          (CLASS, TITLE?, CUSTTEXT?)>

<!-- HEAD/CLASS: Class name (for stylesheet) -->
<!ELEMENT CLASS         (#PCDATA)>

<!-- HEAD/TITLE: The name of this section.  For example, "Starting Places" -->
<!ELEMENT TITLE         (#PCDATA)>
<!-- HEAD/TITLE[VISIBLE]: Should the text be shown on the Start Page? -->
<!ATTLIST TITLE
    VISIBLE (0|1)       "1">

<!-- HEAD/CUSTTEXT: Text to display to allow user to toggle adaptive
     behavior. -->
<!ELEMENT CUSTTEXT      (#PCDATA)>

<!-- IMAGES: A list of IMAGE elements -->
<!ELEMENT IMAGES        (IMAGE*)>

<!-- IMAGE: Just display an image here -->
<!ELEMENT IMAGE         (IMGSRC, HEIGHT, WIDTH)>

<!-- IMAGE[BREAK]: Insert a line break after this image -->
<!ATTLIST IMAGE
    BREAK   (0|1)       "1">

<!-- IMAGE/IMGSRC: The URL for the image itself -->
<!ELEMENT IMGSRC        (#PCDATA)>

<!-- IMAGE/HEIGHT, IMAGE/WIDTH: The dimensions of the image -->
<!ELEMENT HEIGHT        (#PCDATA)>
<!ELEMENT WIDTH         (#PCDATA)>

<!-- ITEM: An actual linkable thingie in the section -->
<!ELEMENT ITEMS         (ITEM*)>
<!ELEMENT ITEM          (TEXT, SUBTEXT?, ICON?, NOTES?, TITLE?, HREF)>

<!-- ITEM[VISIBLE]: Controls visibility of this item -->
<!-- ITEM[NEW]: Is this item new? -->
<!-- ITEM[LINKSTYLE]: How we should launch the target -->
<!-- ITEM[CANPICK]: Can user pick this to hide/show? -->

<!ATTLIST ITEM
    VISIBLE     (0|1)           "1"
    NEW         (0|1)           "0"
    LINKSTYLE   (url|shellexec) #REQUIRED
    CANPICK (0|1)       "1">

<!-- ITEM/TEXT: The text to display for this item -->
<!ELEMENT TEXT          (#PCDATA)>

<!-- ITEM/SUBTEXT: The stuff that goes below the text -->
<!ELEMENT SUBTEXT       (#PCDATA)>

<!-- ITEM/ICON: Optional icon to display at left -->
<!ELEMENT ICON          (#PCDATA)>

<!-- ITEM/NOTES: Notifications -->
<!ELEMENT NOTES         (#PCDATA)>

<!-- ITEM/TITLE: The tooltip to display for the link -->

<!-- ITEM/HREF: The target of the link -->
<!ELEMENT HREF          (#PCDATA)>

<!-- SECTION/LOC: A localizable string -->
<!ELEMENT LOC           (#PCDATA)>
<!ATTLIST LOC
    NAME    CDATA       #REQUIRED>

=== billygoat891/billygoat891.github.io/activity_centers/Start/StartPage/myfiles.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="banner.xsl"?>
<!DOCTYPE SECTION SYSTEM "start.dtd">
<SECTION VISIBLE="1" STYLE="myprograms" MORETARGET="shell:desktopfolder">
	<HEAD>
		<CLASS>myfiles</CLASS>
		<TITLE>My Files and Folders</TITLE>
	</HEAD>
	<ITEMS>
		<ITEM VISIBLE="1" LINKSTYLE="shellexec" CANPICK="1"><TEXT>My Computer</TEXT>
<HREF>::{20D04FE0-3AEA-1069-A2D8-08002B30309D}</HREF>
</ITEM>
<ITEM VISIBLE="1" LINKSTYLE="shellexec" CANPICK="1"><TEXT>My Documents</TEXT>
<HREF>::{450D8FBA-AD25-11D0-98A8-0800361B1103}</HREF>
</ITEM>
<ITEM VISIBLE="1" LINKSTYLE="shellexec" CANPICK="1"><TEXT>Recycle Bin</TEXT>
<HREF>::{645FF040-5081-101B-9F08-00AA002F954E}</HREF>
</ITEM>
<ITEM VISIBLE="0" LINKSTYLE="shellexec" CANPICK="1"><TEXT>My Network Places</TEXT>
<HREF>::{208D2C60-3AEA-1069-A2D7-08002B30309D}</HREF>
</ITEM>
</ITEMS>
	<LOC NAME="more">more...</LOC>
</SECTION>

=== billygoat891/billygoat891.github.io/activity_centers/Start/StartPage/startpl.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="banner.xsl"?>
<!DOCTYPE SECTION SYSTEM "start.dtd">

<SECTION VISIBLE="1" STYLE="startpl" PRIMARY="1">
    <HEAD>
        <CLASS>startingplaces</CLASS>
        <TITLE>Starting Places</TITLE>
    </HEAD>
    <ITEMS>
        <ITEM LINKSTYLE="shellexec" VISIBLE="1">
           <TEXT>E-mail</TEXT>
           <SUBTEXT>Read and send messages</SUBTEXT>
           <ICON>scheme/mail.gif</ICON>
           <HREF>msimn.exe</HREF>
        </ITEM>
        <ITEM LINKSTYLE="shellexec" VISIBLE="1">
           <TEXT>The Internet</TEXT>
           <SUBTEXT>Search the Web, shop, and read news headlines</SUBTEXT>
           <ICON>scheme/ie.gif</ICON>
           <HREF>iexplore.exe</HREF>
        </ITEM>
        <ITEM LINKSTYLE="shellexec" VISIBLE="1">
           <TEXT>Documents</TEXT>
           <SUBTEXT>Write a letter, create a report, and draw a picture</SUBTEXT>
           <ICON>scheme/documents.gif</ICON>
           <HREF>wordpad.exe</HREF>
        </ITEM>
        <ITEM LINKSTYLE="shellexec" VISIBLE="1">
           <TEXT>Music</TEXT>
           <SUBTEXT>Play CDs and record music</SUBTEXT>
           <ICON>scheme/music.gif</ICON>
           <HREF>mediactr.exe</HREF>
        </ITEM>
        <ITEM LINKSTYLE="shellexec" VISIBLE="1">
           <TEXT>Photos</TEXT>
           <SUBTEXT>Edit and share pictures</SUBTEXT>
           <ICON>scheme/photos.gif</ICON>
           <HREF>photoctr.exe</HREF>
        </ITEM>
        <ITEM LINKSTYLE="shellexec" VISIBLE="1">
           <TEXT>Games</TEXT>
           <SUBTEXT>Play games and get game news</SUBTEXT>
           <ICON>scheme/games.gif</ICON>
           <HREF>gamectr.exe</HREF>
        </ITEM>
        <ITEM LINKSTYLE="shellexec" VISIBLE="1">
           <TEXT>Help and Support</TEXT>
           <SUBTEXT>Find Help, fix a problem, and get technical support</SUBTEXT>
           <ICON>scheme/help.gif</ICON>
           <HREF>shell:windows\pchealth\helpctr\binaries\helpctr.exe</HREF>
        </ITEM>
        <ITEM LINKSTYLE="shellexec" VISIBLE="0">
           <TEXT>Type a name here</TEXT>
           <SUBTEXT>Type a description here</SUBTEXT>
           <ICON>scheme/generic.gif</ICON>
           <HREF></HREF>
        </ITEM>
    </ITEMS>

    <LOC NAME="change">Change</LOC>
    <LOC NAME="unused">&lt;unassigned&gt;</LOC>
    <LOC NAME="newname">Type a name here</LOC>
    <LOC NAME="cdtitle">Choose a Starting Place</LOC>
    <LOC NAME="cddefext">*.exe;*.pif;*.com;*.bat;*.cmd</LOC>
    <LOC NAME="cdcombo">|Programs|*.exe;*.pif;*.com;*.bat;*.cmd|All Files|*.*|</LOC>

</SECTION>

=== billygoat891/billygoat891.github.io/activity_centers/Start/StartPage/banner.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="banner.xsl"?>
<!DOCTYPE SECTION SYSTEM "start.dtd">

<SECTION VISIBLE="1" SELECTIVE="0" STYLE="ispbanner">
   <HEAD>
       <CLASS>ispbanner</CLASS>
       <TITLE VISIBLE="0">Product Support</TITLE>
   </HEAD>
   <IMAGES>
      <IMAGE>
           <IMGSRC>scheme\mslogo.gif</IMGSRC>
           <HEIGHT>40</HEIGHT>
           <WIDTH>112</WIDTH>
      </IMAGE>
   </IMAGES>
   <ITEMS>
      <ITEM LINKSTYLE="url">
           <TEXT>Product Support</TEXT>
           <TITLE>Ask a question in plain English</TITLE>
           <HREF>http://support.microsoft.com/support/windows/faq/98/default.asp?FR=0</HREF>
      </ITEM>
      <ITEM LINKSTYLE="url">
           <TEXT>Free Downloads</TEXT>
           <TITLE>Enhance your system with these free downloads from Microsoft.</TITLE>
           <HREF>http://www.microsoft.com/downloads/</HREF>
      </ITEM>
   </ITEMS>
</SECTION>

=== billygoat891/billygoat891.github.io/activity_centers/Start/StartPage/myprograms.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="banner.xsl"?>
<!DOCTYPE SECTION SYSTEM "start.dtd">
<SECTION VISIBLE="1" STYLE="myprograms" ADAPT="1" MORETARGET="shell:programs">
	<HEAD>
		<CLASS>myprograms</CLASS>
		<TITLE>Recent Programs</TITLE>
		<CUSTTEXT>Show the programs I use most often</CUSTTEXT>
	</HEAD>
	<ITEMS>
		<ITEM VISIBLE="1" NEW="1" LINKSTYLE="shellexec"><TEXT>Internet Explorer</TEXT>
<HREF>shell:Start Menu\Programs\Internet Explorer.lnk</HREF>
</ITEM>
<ITEM VISIBLE="1" NEW="1" LINKSTYLE="shellexec"><TEXT>Outlook Express</TEXT>
<HREF>shell:Start Menu\Programs\Outlook Express.lnk</HREF>
</ITEM>
<ITEM VISIBLE="1" NEW="1" LINKSTYLE="shellexec"><TEXT>Windows Media Player</TEXT>
<HREF>shell:Start Menu\Programs\Windows Media Player.lnk</HREF>
</ITEM>
<ITEM VISIBLE="1" NEW="0" LINKSTYLE="shellexec"><TEXT>Programs</TEXT>
<HREF>shell:Start Menu\Programs</HREF>
</ITEM>
<ITEM VISIBLE="0" NEW="0" LINKSTYLE="shellexec"><TEXT></TEXT>
<HREF></HREF>
</ITEM>
<ITEM VISIBLE="0" NEW="0" LINKSTYLE="shellexec"><TEXT></TEXT>
<HREF></HREF>
</ITEM>
</ITEMS>
	<LOC NAME="new">...new</LOC>
	<LOC NAME="more">more...</LOC>
	<LOC NAME="change">Change</LOC>
	<LOC NAME="cdtitle">Choose a Program</LOC>
	<LOC NAME="cddefext">*.exe;*.pif;*.com;*.bat;*.cmd</LOC>
	<LOC NAME="cdcombo">|Programs|*.exe;*.pif;*.com;*.bat;*.cmd|All Files|*.*|</LOC>
</SECTION>
